/* افزونهٔ مستقل: فقط همگام‌سازی موبایل و نمایش لوکیشن‌های صفرموجودی */
(function(){
  function markSyncedGuard(h,status){h.sync='synced';h.excelStatus=status?.excelStatus||'در انتظار';h.syncedAt=h.syncedAt||new Date().toISOString();h.lastSyncError='';h.retryAt=0;if(h.excelStatus==='اعمال شد'&&!h.confirmedAt)h.confirmedAt=new Date().toISOString()}
  function retryDelayGuard(attempts){return Math.min(60000,Math.max(2500,2500*Math.pow(2,Math.min(5,Math.max(0,attempts-1))))+Math.floor(Math.random()*700))}
  function errorTextGuard(error){const text=String(error?.message||error||'خطای نامشخص');if(text==='not confirmed')return'صف پاسخ داد ولی ثبت عملیات را تأیید نکرد.';if(text==='status timeout')return'استعلام وضعیت عملیات پاسخ نداد.';return text}

  syncSummary=function(){const unsent=db.history.filter(h=>h.sync!=='synced').length,retrying=db.history.filter(h=>h.sync==='retry').length,waiting=db.history.filter(h=>h.sync==='synced'&&!excelAppliedStatus(h.excelStatus)&&!excelRejectedStatus(h.excelStatus)).length,review=db.history.filter(h=>h.sync==='synced'&&excelRejectedStatus(h.excelStatus)).length;return{unsent,retrying,waiting,review}}
  showSyncSummary=function(prefix=''){const s=syncSummary();if(s.retrying)syncState(`${prefix}${fa(s.retrying)} عملیات در تلاش مجدد`,false);else if(s.unsent)syncState(`${prefix}${fa(s.unsent)} عملیات در صف ارسال`,false);else if(s.waiting)syncState(`${prefix}${fa(s.waiting)} عملیات رسیده؛ منتظر اکسل`,true);else if(s.review)syncState(`${prefix}${fa(s.review)} عملیات نیازمند بررسی`,false);else syncState(prefix?'به‌روز از اکسل':'همگام',true)}
  sendPendingOperation=async function(h){h.attempts=(h.attempts||0)+1;h.lastAttemptAt=new Date().toISOString();try{if(h.attempts>1){const known=await jsonpStatus(h.id);if(known?.found){markSyncedGuard(h,known);return true}}const pushed=await jsonpPush(h);if(!pushed?.ok)throw Error(pushed?.error||'صف عملیات را نپذیرفت.');const status=await jsonpStatus(h.id);if(!status?.found)throw Error('not confirmed');markSyncedGuard(h,status);return true}catch(error){h.sync='retry';h.lastSyncError=errorTextGuard(error);h.retryAt=Date.now()+retryDelayGuard(h.attempts);return false}}
  syncPending=async function(){if(syncBusy||!db||!db.bridgeKey)return;const allPending=db.history.filter(h=>h.sync!=='synced').slice().reverse();if(!allPending.length){showSyncSummary();setTimeout(refreshStatuses,100);return}if(!navigator.onLine){syncState(`${fa(allPending.length)} در انتظار اینترنت`,false);scheduleSync(8000);return}const due=allPending.filter(h=>!h.retryAt||Number(h.retryAt)<=Date.now());if(!due.length){showSyncSummary();scheduleSync(Math.max(500,Math.min(...allPending.map(h=>Math.max(500,Number(h.retryAt||0)-Date.now())))));return}syncBusy=true;let checked=0;try{for(let i=0;i<due.length;i+=2){const batch=due.slice(i,i+2);syncState(`${fa(checked)} از ${fa(due.length)} در حال بررسی و ارسال…`,false);await Promise.all(batch.map(sendPendingOperation));checked+=batch.length;await encryptJson(db,cryptoKey).then(x=>localStorage.setItem(SECURE_KEY,JSON.stringify(x)))}}finally{syncBusy=false}const left=db.history.filter(h=>h.sync!=='synced').length;showSyncSummary();if(left){const next=Math.min(...db.history.filter(h=>h.sync!=='synced').map(h=>Math.max(500,Number(h.retryAt||0)-Date.now())));scheduleSync(next)}else setTimeout(refreshStatuses,100);renderHistory()}
  operationStatus=function(h){if(h.sync==='retry'){const wait=Math.max(0,Math.ceil((Number(h.retryAt||0)-Date.now())/1000)),reason=h.lastSyncError?`؛ ${h.lastSyncError}`:'';return wait?`ارسال ناموفق${reason}؛ تلاش مجدد تا ${fa(wait)} ثانیه`:`ارسال ناموفق${reason}؛ در حال تلاش مجدد`}if(h.sync!=='synced')return'در حال ارسال';if(excelAppliedStatus(h.excelStatus))return'اعمال شد ✓';if(excelRejectedStatus(h.excelStatus))return'نیازمند بررسی ⚠';return'منتظر اکسل'}
  inProductInfo=function(){const code=norm(document.querySelector('#inProduct').value),p=product(code),rows=code?db.stock.filter(x=>x.p===code&&x.l):[];if(p)document.querySelector('#inOccasion').value=p.occasion||p.name||'';const total=rows.reduce((a,x)=>a+Math.max(0,Number(x.q)||0),0),locations=rows.length?rows.map(x=>`<span class="badge">${html(x.display||x.l)}: ${fa(x.q)}</span>`).join(''):'<span class="badge">لوکیشن ثبت‌شده‌ای ندارد</span>';document.querySelector('#inExisting').innerHTML=!code?'':`<div class="shared-box"><strong>${p?'موجودی فعلی '+html(code):'کد جدید'}</strong><div class="split-summary"><span class="badge">مجموع ${fa(total)}</span>${locations}</div></div>`;renderInRows()}
  const inProductField=document.querySelector('#inProduct');
  if(inProductField)inProductField.oninput=inProductInfo;
})();
