"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, Clock3, LogOut, Plus, RefreshCw, Search, Settings2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";

type User={id:number;email:string;displayName:string;role:string};
type StageEvent={id:number;fromStage:string;toStage:string;actorEmail:string;actorRole:string;note:string;createdAt:string};
type Job={id:number;code:string;quantity:number;customer:string;occasion:string;route:string;currentStage:string;status:string;createdAt:string;updatedAt:string;events:StageEvent[]};
const fa:Record<string,string>={pending:"در انتظار تأیید",admin:"مدیر",new:"ثبت سفارش",plotter:"پلاتر",calendar:"کلندر",laser:"لیزر",sewing:"خیاط قدیمی",sewing1:"خیاط ۱",sewing2:"خیاط ۲",sewing3:"خیاط ۳",warehouse:"انبار",completed:"تکمیل‌شده"};
const stages=["plotter","calendar","laser","sewing1","sewing2","sewing3","warehouse"];
const tailors=["sewing1","sewing2","sewing3"] as const;
const roleChoices=["pending","admin",...stages,"sewing"];
const when=(value:string)=>new Date(value).toLocaleString("fa-IR-u-ca-persian",{timeZone:"Asia/Tehran",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"});

export default function TrackerClient(){
 const[me,setMe]=useState<User|null>(null),[users,setUsers]=useState<User[]>([]),[jobs,setJobs]=useState<Job[]>([]),[search,setSearch]=useState(""),[busy,setBusy]=useState<number|null>(null),[msg,setMsg]=useState(""),[paste,setPaste]=useState(""),[create,setCreate]=useState(false),[manage,setManage]=useState(false),[tailor,setTailor]=useState<Record<number,string>>({});
 const loadJobs=useCallback(async()=>{try{const r=await fetch("/api/jobs",{cache:"no-store"}),d=await r.json();if(r.ok)setJobs(d.jobs??[])}catch{setMsg("ارتباط با سرور برقرار نشد")}},[]);
 const load=useCallback(async()=>{try{const[s,j]=await Promise.all([fetch("/api/session",{cache:"no-store"}),fetch("/api/jobs",{cache:"no-store"})]);const sd=await s.json(),jd=await j.json();setMe(sd.user);setUsers(sd.users??[]);setJobs(jd.jobs??[])}catch{setMsg("ارتباط با سرور برقرار نشد")}},[]);
 useEffect(()=>{load();const id=setInterval(loadJobs,8000);return()=>clearInterval(id)},[load,loadJobs]);
 const shown=useMemo(()=>jobs.filter(j=>`${j.code} ${j.customer} ${fa[j.currentStage]||j.currentStage}`.toLowerCase().includes(search.toLowerCase())),[jobs,search]);
 const stageCount=(stage:string)=>jobs.filter(j=>stage==="sewing1"?(j.currentStage==="sewing1"||j.currentStage==="sewing"):j.currentStage===stage).length;
 async function advance(j:Job,route?:"laser"|"direct",tailorStage?:string){setBusy(j.id);try{const r=await fetch(`/api/jobs/${j.id}/advance`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({route,tailor:tailorStage})}),d=await r.json();setMsg(r.ok?`کد ${j.code} از ${fa[d.event.fromStage]||d.event.fromStage} به ${fa[d.event.toStage]||d.event.toStage} منتقل شد`:d.error);if(r.ok)setJobs(old=>old.map(x=>x.id===j.id?{...d.job,events:[d.event,...(x.events||[])]}:x))}catch{setMsg("انتقال انجام نشد؛ دوباره تلاش کنید")}finally{setBusy(null)}}
 async function add(){const rows=paste.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(line=>{const p=line.split(/\t|,/);return{code:(p[0]??"").trim(),quantity:Number(p[1])||1,customer:(p[2]??"").trim()}});const r=await fetch("/api/jobs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({rows})}),d=await r.json();setMsg(r.ok?`${d.count} سفارش در تاریخ و ساعت فعلی به پلاتر فرستاده شد`:d.error);if(r.ok){setPaste("");setCreate(false);await loadJobs()}}
 async function role(id:number,value:string){await fetch(`/api/users/${id}/role`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({role:value})});await load()}
 if(!me)return <main className="center"><RefreshCw className="spin"/><p>در حال اتصال…</p></main>;
 if(me.role==="pending")return <main className="center pending"><Clock3/><h1>در انتظار تأیید مدیر</h1><p>حساب شما ثبت شد. مدیر باید واحد کاری شما را تعیین کند.</p><Button onClick={load}>بررسی دوباره</Button></main>;
 return <main><header className="topbar"><div><span>سامانه زنده تولید</span><h1>پیگیری سفارش‌ها</h1></div><div className="identity"><div><span>{me.displayName}</span><b>{fa[me.role]||me.role}</b></div><a href="/signout-with-chatgpt?return_to=/" aria-label="خروج"><LogOut/></a></div></header>
 <section className="toolbar"><div className="search"><Search/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="جست‌وجوی کد، مشتری یا واحد"/></div><Button variant="outline" onClick={loadJobs}><RefreshCw/>تازه‌سازی</Button>{me.role==="admin"&&<>
 <Dialog open={create} onOpenChange={setCreate}><DialogTrigger render={<Button><Plus/>سفارش جدید</Button>}/><DialogContent dir="rtl"><DialogHeader><DialogTitle>ورود گروهی سفارش</DialogTitle><DialogDescription>از اکسل سه ستون کد، تعداد و مشتری را کپی کنید؛ تاریخ شمسی و ساعت به‌صورت خودکار ثبت می‌شود.</DialogDescription></DialogHeader><Textarea rows={9} value={paste} onChange={e=>setPaste(e.target.value)} placeholder={"10-1280\t4\tعباس"}/><Button onClick={add}>ثبت و ارسال به پلاتر</Button></DialogContent></Dialog>
 <Dialog open={manage} onOpenChange={setManage}><DialogTrigger render={<Button variant="outline"><Settings2/>کاربران</Button>}/><DialogContent dir="rtl"><DialogHeader><DialogTitle>دسترسی واحدها</DialogTitle><DialogDescription>هر شخص فقط سفارش‌های واحد خودش را می‌بیند.</DialogDescription></DialogHeader><div className="users">{users.map(u=><div className="user" key={u.id}><div><b>{u.displayName}</b><small>{u.email}</small></div><select value={u.role} disabled={u.email===me.email} onChange={e=>role(u.id,e.target.value)}>{roleChoices.map(r=><option key={r} value={r}>{fa[r]}</option>)}</select></div>)}</div></DialogContent></Dialog></>}</section>
 {msg&&<div className="notice">{msg}</div>}{me.role==="admin"&&<section className="stats">{[...stages,"completed"].map(s=><div key={s} className={`stat s-${s}`}><span>{fa[s]}</span><strong>{stageCount(s)}</strong></div>)}</section>}
 <section className="section-head"><div><h2>{me.role==="admin"?"همه سفارش‌ها":`کارهای واحد ${fa[me.role]||me.role}`}</h2><p>اطلاعات هر ۸ ثانیه خودکار تازه می‌شود</p></div><span>{shown.length} مورد</span></section>
 <section className="jobs">{shown.map(j=>{const chosenTailor=tailor[j.id]||"sewing1";const latest=j.events?.[0];return <article className="job" key={j.id}><div className="job-head"><div><span className={`stage stage-${j.currentStage}`}>{fa[j.currentStage]||j.currentStage}</span><h3 dir="ltr">{j.code}</h3></div><strong>{j.quantity}<small> عدد</small></strong></div><div className="meta"><span>مشتری<b>{j.customer||"—"}</b></span><span>تاریخ ثبت<b>{when(j.createdAt)}</b></span><span>آخرین انتقال<b>{latest?`از ${fa[latest.fromStage]||latest.fromStage} به ${fa[latest.toStage]||latest.toStage} | ${when(latest.createdAt)}`:"—"}</b></span></div>
 {j.events?.length>0&&<details className="transfer-history"><summary>مشاهده سابقه انتقال‌ها</summary><div>{j.events.map(e=><p key={e.id}><b>از {fa[e.fromStage]||e.fromStage} به {fa[e.toStage]||e.toStage}</b><span>{when(e.createdAt)}</span></p>)}</div></details>}
 {j.status==="active"&&(me.role==="admin"||me.role===j.currentStage||(me.role==="sewing1"&&j.currentStage==="sewing"))&&<div className="actions">{j.currentStage==="calendar"?<><Button onClick={()=>advance(j,"laser")} disabled={busy===j.id}>نیاز به لیزر</Button><select className="tailor-select" aria-label="انتخاب خیاط" value={chosenTailor} onChange={e=>setTailor(old=>({...old,[j.id]:e.target.value}))}>{tailors.map(t=><option key={t} value={t}>{fa[t]}</option>)}</select><Button variant="outline" onClick={()=>advance(j,"direct",chosenTailor)} disabled={busy===j.id}>مستقیم به {fa[chosenTailor]}</Button></>:j.currentStage==="laser"?<><select className="tailor-select" aria-label="انتخاب خیاط" value={chosenTailor} onChange={e=>setTailor(old=>({...old,[j.id]:e.target.value}))}>{tailors.map(t=><option key={t} value={t}>{fa[t]}</option>)}</select><Button onClick={()=>advance(j,undefined,chosenTailor)} disabled={busy===j.id}><CheckCircle2/>{busy===j.id?"در حال انتقال…":`ارسال به ${fa[chosenTailor]}`}</Button></>:<Button onClick={()=>advance(j)} disabled={busy===j.id}><CheckCircle2/>{busy===j.id?"در حال انتقال…":j.currentStage==="warehouse"?"تحویل شد و تکمیل":"مرحله انجام شد"}</Button>}</div>}</article>})}{!shown.length&&<div className="empty"><CheckCircle2/><h3>کاری در این بخش نیست</h3><p>به محض رسیدن سفارش جدید، اینجا نمایش داده می‌شود.</p></div>}</section></main>
}
