"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, Clock3, LogOut, Plus, RefreshCw, Search, Settings2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
type User={id:number;email:string;displayName:string;role:string}; type Job={id:number;code:string;quantity:number;customer:string;occasion:string;route:string;currentStage:string;status:string;updatedAt:string};
const fa:Record<string,string>={pending:"در انتظار تأیید",admin:"مدیر",plotter:"پلاتر",calendar:"کلندر",laser:"لیزر",sewing:"خیاط",warehouse:"انبار",completed:"تکمیل‌شده"};
const stages=["plotter","calendar","laser","sewing","warehouse"];
export default function TrackerClient(){
 const[me,setMe]=useState<User|null>(null),[users,setUsers]=useState<User[]>([]),[jobs,setJobs]=useState<Job[]>([]),[search,setSearch]=useState(""),[busy,setBusy]=useState<number|null>(null),[msg,setMsg]=useState(""),[paste,setPaste]=useState(""),[create,setCreate]=useState(false),[manage,setManage]=useState(false);
 const load=useCallback(async()=>{try{const[s,j]=await Promise.all([fetch("/api/session"),fetch("/api/jobs")]);const sd=await s.json(),jd=await j.json();setMe(sd.user);setUsers(sd.users??[]);setJobs(jd.jobs??[])}catch{setMsg("ارتباط با سرور برقرار نشد")}},[]);
 useEffect(()=>{load();const id=setInterval(load,8000);return()=>clearInterval(id)},[load]);
 const shown=useMemo(()=>jobs.filter(j=>`${j.code} ${j.customer} ${j.occasion}`.toLowerCase().includes(search.toLowerCase())),[jobs,search]);
 async function advance(j:Job,route?:"laser"|"direct"){setBusy(j.id);const r=await fetch(`/api/jobs/${j.id}/advance`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({route})}),d=await r.json();setMsg(r.ok?`کد ${j.code} به ${fa[d.next]} منتقل شد`:d.error);if(r.ok)await load();setBusy(null)}
 async function add(){const rows=paste.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(line=>{const p=line.split(/\t|,/);return{code:(p[0]??"").trim(),quantity:Number(p[1])||1,customer:(p[2]??"").trim(),occasion:(p[3]??"").trim()}});const r=await fetch("/api/jobs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({rows})}),d=await r.json();setMsg(r.ok?`${d.count} سفارش به پلاتر فرستاده شد`:d.error);if(r.ok){setPaste("");setCreate(false);await load()}}
 async function role(id:number,value:string){await fetch(`/api/users/${id}/role`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({role:value})});await load()}
 if(!me)return <main className="center"><RefreshCw className="spin"/><p>در حال اتصال…</p></main>;
 if(me.role==="pending")return <main className="center pending"><Clock3/><h1>در انتظار تأیید مدیر</h1><p>حساب شما ثبت شد. مدیر باید واحد کاری شما را تعیین کند.</p><Button onClick={load}>بررسی دوباره</Button></main>;
 return <main><header className="topbar"><div><span>سامانه زنده تولید</span><h1>پیگیری سفارش‌ها</h1></div><div className="identity"><div><span>{me.displayName}</span><b>{fa[me.role]}</b></div><a href="/signout-with-chatgpt?return_to=/" aria-label="خروج"><LogOut/></a></div></header>
 <section className="toolbar"><div className="search"><Search/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="جست‌وجوی کد، مشتری یا مناسبت"/></div><Button variant="outline" onClick={load}><RefreshCw/>تازه‌سازی</Button>{me.role==="admin"&&<>
 <Dialog open={create} onOpenChange={setCreate}><DialogTrigger render={<Button><Plus/>سفارش جدید</Button>}/><DialogContent dir="rtl"><DialogHeader><DialogTitle>ورود گروهی سفارش</DialogTitle><DialogDescription>از اکسل چهار ستون کد، تعداد، مشتری و مناسبت را کپی کنید.</DialogDescription></DialogHeader><Textarea rows={9} value={paste} onChange={e=>setPaste(e.target.value)} placeholder={"10-1280\t4\tعباس\tمحرم و صفر"}/><Button onClick={add}>ثبت و ارسال به پلاتر</Button></DialogContent></Dialog>
 <Dialog open={manage} onOpenChange={setManage}><DialogTrigger render={<Button variant="outline"><Settings2/>کاربران</Button>}/><DialogContent dir="rtl"><DialogHeader><DialogTitle>دسترسی واحدها</DialogTitle><DialogDescription>هر شخص فقط سفارش‌های واحد خودش را می‌بیند.</DialogDescription></DialogHeader><div className="users">{users.map(u=><div className="user" key={u.id}><div><b>{u.displayName}</b><small>{u.email}</small></div><select value={u.role} disabled={u.email===me.email} onChange={e=>role(u.id,e.target.value)}>{["pending","admin",...stages].map(r=><option key={r} value={r}>{fa[r]}</option>)}</select></div>)}</div></DialogContent></Dialog></>}</section>
 {msg&&<div className="notice">{msg}</div>}{me.role==="admin"&&<section className="stats">{[...stages,"completed"].map(s=><div key={s} className={`stat s-${s}`}><span>{fa[s]}</span><strong>{jobs.filter(j=>j.currentStage===s).length}</strong></div>)}</section>}
 <section className="section-head"><div><h2>{me.role==="admin"?"همه سفارش‌ها":`کارهای واحد ${fa[me.role]}`}</h2><p>اطلاعات هر ۸ ثانیه خودکار تازه می‌شود</p></div><span>{shown.length} مورد</span></section>
 <section className="jobs">{shown.map(j=><article className="job" key={j.id}><div className="job-head"><div><span className={`stage stage-${j.currentStage}`}>{fa[j.currentStage]}</span><h3 dir="ltr">{j.code}</h3></div><strong>{j.quantity}<small> عدد</small></strong></div><div className="meta"><span>مشتری<b>{j.customer||"—"}</b></span><span>مناسبت<b>{j.occasion||"—"}</b></span><span>آخرین تغییر<b>{new Date(j.updatedAt).toLocaleString("fa-IR",{dateStyle:"short",timeStyle:"short"})}</b></span></div>
 {j.status==="active"&&(me.role==="admin"||me.role===j.currentStage)&&<div className="actions">{j.currentStage==="calendar"?<><Button onClick={()=>advance(j,"laser")} disabled={busy===j.id}>نیاز به لیزر</Button><Button variant="outline" onClick={()=>advance(j,"direct")} disabled={busy===j.id}>مستقیم به خیاط</Button></>:<Button onClick={()=>advance(j)} disabled={busy===j.id}><CheckCircle2/>{j.currentStage==="warehouse"?"تحویل شد و تکمیل":"مرحله انجام شد"}</Button>}</div>}</article>)}{!shown.length&&<div className="empty"><CheckCircle2/><h3>کاری در این بخش نیست</h3><p>به محض رسیدن سفارش جدید، اینجا نمایش داده می‌شود.</p></div>}</section></main>
}
