const SHEET_ID="13MRxSoqVZjRAii4qs4dwgAkd6WBN7qBzAblw4rVFjA0";
const INITIAL_ADMIN_PASSWORD="رمز-دلخواه-خودتان";
const STAGES=["plotter","calendar","laser","sewing","warehouse","completed"];
function out(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
function doGet(){return out({ok:true,name:"سامانه پیگیری تولید نبراس"})}
function doPost(e){try{const q=JSON.parse(e.postData.contents||"{}");if(q.action==="login")return out(login(q));const u=sessionUser(q.session);if(!u)return out({ok:false,error:"نشست شما منقضی شده است"});if(q.action==="list")return out(list(u));if(q.action==="add")return out(add(u,q));if(q.action==="advance")return out(advance(u,q));return out({ok:false,error:"درخواست نامعتبر"})}catch(x){return out({ok:false,error:String(x.message||x)})}}
function sh(n){return SpreadsheetApp.openById(SHEET_ID).getSheetByName(n)}
function hash(x){const b=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,x,Utilities.Charset.UTF_8);return b.map(v=>(v+256)%256).map(v=>v.toString(16).padStart(2,"0")).join("")}
function secret(){const p=PropertiesService.getScriptProperties();let s=p.getProperty("SECRET");if(!s){s=Utilities.getUuid()+Utilities.getUuid();p.setProperty("SECRET",s)}return s}
function setupAdmin(){const password=INITIAL_ADMIN_PASSWORD.trim();if(password==="رمز-دلخواه-خودتان"||password.length<4)throw new Error("ابتدا مقدار INITIAL_ADMIN_PASSWORD را به رمز دلخواه خود تغییر دهید");sh("کاربران").getRange(2,5).setValue(hash(password));Logger.log("رمز مدیر با موفقیت تنظیم شد")}
function rows(n){const s=sh(n),v=s.getDataRange().getValues();return v.slice(1)}
function login(q){const u=rows("کاربران").find(r=>String(r[0]).trim()===String(q.username).trim()&&r[3]!==false);if(!u)return {ok:false,error:"نام کاربری پیدا نشد"};if(!u[4])return {ok:false,error:"ابتدا تابع setupAdmin را اجرا و رمز مدیر را تنظیم کنید"};if(u[4]!==hash(q.password))return {ok:false,error:"رمز عبور اشتباه است"};const until=Date.now()+86400000*7,payload=[u[0],u[1],roleKey(u[2]),until].join("|"),sig=hash(payload+"|"+secret());return {ok:true,session:Utilities.base64EncodeWebSafe(payload+"|"+sig)}}
function sessionUser(t){try{const raw=Utilities.newBlob(Utilities.base64DecodeWebSafe(t)).getDataAsString(),p=raw.split("|"),sig=p.pop();if(hash(p.join("|")+"|"+secret())!==sig||Date.now()>+p[3])return null;return {username:p[0],name:p[1],role:p[2]}}catch(e){return null}}
function roleKey(x){return {"مدیر":"admin","پلاتر":"plotter","کلندر":"calendar","لیزر":"laser","خیاط":"sewing","انبار":"warehouse"}[x]||x}
function list(u){const data=rows("سفارش‌ها").filter(r=>r[0]!==""),jobs=data.map(r=>({id:+r[0],code:String(r[1]),quantity:+r[2],customer:String(r[3]||""),occasion:String(r[4]||""),route:String(r[5]||""),stage:roleKey(r[6]),status:String(r[7]),canAdvance:u.role==="admin"||u.role===roleKey(r[6])}));return {ok:true,user:u,jobs:u.role==="admin"?jobs:jobs.filter(j=>j.stage===u.role)}}
function add(u,q){if(u.role!=="admin")return {ok:false,error:"فقط مدیر می‌تواند سفارش ثبت کند"};const s=sh("سفارش‌ها"),id=Math.max(0,...rows("سفارش‌ها").map(r=>+r[0]||0))+1,now=new Date();s.appendRow([id,q.code,+q.quantity||1,q.customer||"",q.occasion||"","عادی","پلاتر","فعال","",u.username,now,now,""]);return {ok:true,id}}
function advance(u,q){const s=sh("سفارش‌ها"),v=s.getDataRange().getValues(),i=v.findIndex((r,n)=>n>0&&+r[0]===+q.id);if(i<1)return {ok:false,error:"سفارش پیدا نشد"};const from=roleKey(v[i][6]);if(u.role!=="admin"&&u.role!==from)return {ok:false,error:"این سفارش مربوط به واحد شما نیست"};let to;if(from==="calendar")to=q.route==="direct"?"sewing":"laser";else to=STAGES[STAGES.indexOf(from)+1];const fa={plotter:"پلاتر",calendar:"کلندر",laser:"لیزر",sewing:"خیاط",warehouse:"انبار",completed:"تکمیل‌شده"};s.getRange(i+1,7).setValue(fa[to]);s.getRange(i+1,8).setValue(to==="completed"?"تکمیل‌شده":"فعال");s.getRange(i+1,12).setValue(new Date());if(to==="completed")s.getRange(i+1,13).setValue(new Date());sh("تاریخچه مراحل").appendRow([Date.now(),q.id,fa[from],fa[to],u.username,fa[u.role]||u.role,"",new Date()]);return {ok:true,next:to}}
