const SHEET_ID="13MRxSoqVZjRAii4qs4dwgAkd6WBN7qBzAblw4rVFjA0";
const INITIAL_ADMIN_PASSWORD="رمز-دلخواه-خودتان";
const ROLE_FA={admin:"مدیر",plotter:"پلاتر",calendar:"کلندر",cutting:"برش",laser:"لیزر",sewing:"خیاط قدیمی",sewing1:"خیاط ۱",sewing2:"خیاط ۲",sewing3:"خیاط ۳",warehouse:"انبار",completed:"تکمیل‌شده",new:"ثبت سفارش"};
const MAX_TAILORS=20;

function out(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
function doGet(){return out({ok:true,name:"سامانه پیگیری تولید نبراس"})}
function doPost(e){try{const q=JSON.parse(e.postData.contents||"{}");if(q.action==="login")return out(login(q));const u=sessionUser(q.session);if(!u)return out({ok:false,error:"نشست شما منقضی شده است"});const a={list,listUsers,add,addUser,updateUser,advance,complete,editJob,clearArchive};return out(a[q.action]?a[q.action](u,q):{ok:false,error:"درخواست نامعتبر"})}catch(x){return out({ok:false,error:String(x.message||x)})}}
function sh(n){return SpreadsheetApp.openById(SHEET_ID).getSheetByName(n)}
function rows(n){return sh(n).getDataRange().getValues().slice(1)}
function hash(x){const b=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,x,Utilities.Charset.UTF_8);return b.map(v=>(v+256)%256).map(v=>v.toString(16).padStart(2,"0")).join("")}
function setupAdmin(){const p=INITIAL_ADMIN_PASSWORD.trim();if(p==="رمز-دلخواه-خودتان"||p.length<4)throw Error("ابتدا رمز مدیر را تنظیم کنید");sh("کاربران").getRange(2,5).setValue(hash(p))}
function nowFa(d){return new Intl.DateTimeFormat("fa-IR-u-ca-persian-nu-latn",{timeZone:"Asia/Tehran",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(d||new Date()).replace(/،|,/g,"")}
function roleKey(x){return {"مدیر":"admin","پلاتر":"plotter","کلندر":"calendar","برش":"cutting","لیزر":"laser","خیاط":"sewing","خیاط قدیمی":"sewing","خیاط ۱":"sewing1","خیاط ۲":"sewing2","خیاط ۳":"sewing3","انبار":"warehouse","تکمیل‌شده":"completed","تکمیل شده":"completed","ثبت سفارش":"new"}[String(x||"").trim()]||String(x||"").trim()}
function isTailorRole(x){return x==="sewing"||/^sewing(?:[1-9]|1\d|20)$/.test(String(x||""))}
function allTailors(){return rows("کاربران").map(r=>({username:String(r[0]||""),name:String(r[1]||""),role:roleKey(r[2]),active:r[3]!==false})).filter(x=>x.username&&isTailorRole(x.role))}
function activeTailorRoles(){return allTailors().filter(x=>x.active).map(x=>x.role)}
function storedStage(r){const stage=roleKey(r[6]),tailor=roleKey(r[5]);return stage==="sewing"&&isTailorRole(tailor)?tailor:stage}
function roleFa(x){if(ROLE_FA[x])return ROLE_FA[x];const tailor=allTailors().find(t=>t.role===x);return tailor?"خیاط ـ "+tailor.name:"خیاط"}
function newTailorRole(){const current=allTailors(),used=new Set(current.map(x=>x.role));if(current.length>=MAX_TAILORS)throw Error("حداکثر ۲۰ خیاط تعریف شده است");for(let i=1;i<=MAX_TAILORS;i++)if(!used.has("sewing"+i))return "sewing"+i;throw Error("حداکثر ۲۰ خیاط تعریف شده است")}
function canHandle(u,s){return u.role==="admin"||u.role===s||(u.role==="sewing1"&&s==="sewing")}
function nextId(v){return Math.max(0,...v.slice(1).map(r=>+r[0]||0))+1}
function history(id,from,to,u,note,stamp){const h=sh("تاریخچه مراحل"),eid=Date.now();h.appendRow([eid,id,roleFa(from),roleFa(to),u.username,roleFa(u.role),note||"",stamp]);h.getRange(h.getLastRow(),8).setNumberFormat("@");return {id:eid,fromStage:from,toStage:to,actor:u.username,actorRole:u.role,note:note||"",createdAt:stamp}}
function eventMap(){const m={};rows("تاریخچه مراحل").forEach((r,i)=>{const id=String(r[1]||"");if(!id)return;const e={id:+r[0]||i+1,fromStage:roleKey(r[2]),toStage:roleKey(r[3]),actor:String(r[4]||""),actorRole:roleKey(r[5]),note:String(r[6]||""),createdAt:String(r[7]||"")};(m[id]||(m[id]=[])).push(e)});Object.keys(m).forEach(id=>m[id].sort((a,b)=>b.id-a.id));return m}
function jobRow(r,d,i,u,ev){const stage=storedStage(r);return{id:+r[0],code:String(d[i][1]),quantity:+r[2],customer:String(r[3]||""),occasion:String(r[4]||""),route:String(r[5]||""),stage,status:String(r[7]),progress:+r[8]||0,createdAt:String(r[10]||""),updatedAt:String(r[11]||""),completedAt:String(r[12]||""),events:(ev[String(r[0])]||[]).slice(0,30),canAdvance:canHandle(u,stage)}}
function sessionUser(t){try{if(!t)return null;const p=PropertiesService.getScriptProperties(),k="SESSION_"+t,r=p.getProperty(k);if(!r)return null;const u=JSON.parse(r);if(Date.now()>+u.until){p.deleteProperty(k);return null}return{username:u.username,name:u.name,role:u.role}}catch(e){return null}}
function login(q){const u=rows("کاربران").find(r=>String(r[0]).trim()===String(q.username).trim()&&r[3]!==false);if(!u)return{ok:false,error:"نام کاربری پیدا نشد"};if(!u[4])return{ok:false,error:"ابتدا رمز مدیر را تنظیم کنید"};if(u[4]!==hash(q.password))return{ok:false,error:"رمز عبور اشتباه است"};const t=Utilities.getUuid().replace(/-/g,"")+Utilities.getUuid().replace(/-/g,"");PropertiesService.getScriptProperties().setProperty("SESSION_"+t,JSON.stringify({username:String(u[0]),name:String(u[1]),role:roleKey(u[2]),until:Date.now()+604800000}));return{ok:true,session:t}}
function list(u){const s=sh("سفارش‌ها"),r=s.getDataRange().getValues().slice(1),d=s.getDataRange().getDisplayValues().slice(1),ev=eventMap(),jobs=[];r.forEach((x,i)=>{if(x[0]!=="")jobs.push(jobRow(x,d,i,u,ev))});return{ok:true,user:u,tailors:allTailors(),jobs:u.role==="admin"?jobs:jobs.filter(j=>j.stage===u.role||(u.role==="sewing1"&&j.stage==="sewing"))}}
function add(u,q){if(u.role!=="admin")return{ok:false,error:"فقط مدیر می‌تواند سفارش ثبت کند"};const s=sh("سفارش‌ها"),id=nextId(s.getDataRange().getValues()),stamp=nowFa(),row=s.getLastRow()+1;s.getRange(row,2).setNumberFormat("@");s.getRange(row,11,1,3).setNumberFormat("@");s.getRange(row,1,1,13).setValues([[id,String(q.code),+q.quantity||1,q.customer||"","","تعیین‌نشده","پلاتر","فعال",0,u.username,stamp,stamp,""]]);const e=history(id,"new","plotter",u,"ثبت سفارش",stamp);return{ok:true,id,event:e}}
function rolesFa(){return{admin:"مدیر",plotter:"پلاتر",calendar:"کلندر",cutting:"برش",laser:"لیزر",warehouse:"انبار"}}
function addUser(u,q){if(u.role!=="admin")return{ok:false,error:"فقط مدیر می‌تواند کاربر بسازد"};const n=String(q.username||"").trim(),name=String(q.name||"").trim(),p=String(q.password||""),roles=rolesFa(),role=q.role==="sewing_new"?newTailorRole():q.role;if(!n||!name||(!roles[role]&&!isTailorRole(role)))return{ok:false,error:"اطلاعات کاربر کامل نیست"};if(p.length<4)return{ok:false,error:"رمز باید حداقل ۴ کاراکتر باشد"};if(rows("کاربران").some(r=>String(r[0]).trim()===n))return{ok:false,error:"این نام کاربری قبلاً ثبت شده است"};sh("کاربران").appendRow([n,name,roles[role]||role,true,hash(p)]);return{ok:true,role}}
function listUsers(u){if(u.role!=="admin")return{ok:false,error:"فقط مدیر به کاربران دسترسی دارد"};return{ok:true,users:rows("کاربران").map(r=>({username:String(r[0]||""),name:String(r[1]||""),role:roleKey(r[2]),active:r[3]!==false})).filter(x=>x.username)}}
function updateUser(u,q){if(u.role!=="admin")return{ok:false,error:"فقط مدیر می‌تواند کاربران را ویرایش کند"};const s=sh("کاربران"),v=s.getDataRange().getValues(),old=String(q.originalUsername||"").trim(),i=v.findIndex((r,n)=>n>0&&String(r[0]).trim()===old),n=String(q.username||"").trim(),name=String(q.name||"").trim(),p=String(q.password||""),roles=rolesFa();if(i<1)return{ok:false,error:"کاربر پیدا نشد"};const oldRole=roleKey(v[i][2]),role=q.role==="sewing_new"?(isTailorRole(oldRole)?oldRole:newTailorRole()):q.role;if(!n||!name||(!roles[role]&&!isTailorRole(role)))return{ok:false,error:"اطلاعات کاربر کامل نیست"};if(v.some((r,k)=>k>0&&k!==i&&String(r[0]).trim()===n))return{ok:false,error:"این نام کاربری قبلاً استفاده شده است"};if(p&&p.length<4)return{ok:false,error:"رمز جدید باید حداقل ۴ کاراکتر باشد"};if(old===u.username&&q.active===false)return{ok:false,error:"حساب فعلی قابل غیرفعال‌کردن نیست"};if(isTailorRole(oldRole)&&role!==oldRole&&rows("سفارش‌ها").some(r=>storedStage(r)===oldRole))return{ok:false,error:"این خیاط سفارش فعال دارد؛ ابتدا سفارش‌هایش را منتقل کنید"};s.getRange(i+1,1,1,4).setValues([[n,name,roles[role]||role,q.active!==false]]);if(p)s.getRange(i+1,5).setValue(hash(p));return{ok:true,role}}
function resolveNext(from,q){const active=activeTailorRoles();if(from==="plotter")return{to:"calendar",route:""};if(from==="calendar"){if(q.route==="laser")return{to:"laser",route:"لیزر"};if(q.route==="cutting")return{to:"cutting",route:"برش"};if(q.route==="direct"&&active.includes(q.tailor))return{to:q.tailor,route:q.tailor};throw Error("مسیر یا خیاط فعال مقصد را انتخاب کنید")};if(from==="cutting"||from==="laser"){if(!active.includes(q.tailor))throw Error("یک خیاط فعال را انتخاب کنید");return{to:q.tailor,route:q.tailor}};if(isTailorRole(from))return{to:"warehouse",route:""};if(from==="warehouse")return{to:"completed",route:""};throw Error("مرحله بعدی تعریف نشده است")}
function advance(u,q){const s=sh("سفارش‌ها"),v=s.getDataRange().getValues(),i=v.findIndex((r,n)=>n>0&&+r[0]===+q.id);if(i<1)return{ok:false,error:"سفارش پیدا نشد"};const from=storedStage(v[i]);if(!canHandle(u,from))return{ok:false,error:"این سفارش مربوط به واحد شما نیست"};const m=resolveNext(from,q),stamp=nowFa();if(m.route)s.getRange(i+1,6).setValue(m.route);s.getRange(i+1,7).setValue(isTailorRole(m.to)?"خیاط":ROLE_FA[m.to]);s.getRange(i+1,8).setValue(m.to==="completed"?"تکمیل‌شده":"فعال");s.getRange(i+1,9).setValue(0);s.getRange(i+1,12).setNumberFormat("@").setValue(stamp);if(m.to==="completed")s.getRange(i+1,13).setNumberFormat("@").setValue(stamp);return{ok:true,next:m.to,event:history(q.id,from,m.to,u,q.note||"",stamp)}}
function complete(u,q){if(u.role!=="admin")return{ok:false,error:"فقط مدیر می‌تواند سفارش را مستقیم تکمیل کند"};const s=sh("سفارش‌ها"),v=s.getDataRange().getValues(),i=v.findIndex((r,n)=>n>0&&+r[0]===+q.id);if(i<1)return{ok:false,error:"سفارش پیدا نشد"};const from=storedStage(v[i]),stamp=nowFa();if(from==="completed")return{ok:true,next:"completed"};s.getRange(i+1,7,1,3).setValues([["تکمیل‌شده","تکمیل‌شده",0]]);s.getRange(i+1,12,1,2).setNumberFormat("@").setValues([[stamp,stamp]]);return{ok:true,next:"completed",event:history(q.id,from,"completed",u,"تکمیل مستقیم توسط مدیر",stamp)}}
function editJob(u,q){const s=sh("سفارش‌ها"),v=s.getDataRange().getValues(),i=v.findIndex((r,n)=>n>0&&+r[0]===+q.id);if(i<1)return{ok:false,error:"سفارش پیدا نشد"};const from=storedStage(v[i]),total=Math.floor(+q.quantity||0),done=Math.floor(+q.progress||0);if(!canHandle(u,from))return{ok:false,error:"این سفارش مربوط به واحد شما نیست"};if(total<1||done<0||done>total)return{ok:false,error:"تعداد واردشده صحیح نیست"};const stamp=nowFa();s.getRange(i+1,2,1,3).setValues([[String(q.code||v[i][1]),total,String(q.customer||"")]]);s.getRange(i+1,5).setValue("");if(!q.sendCompleted){s.getRange(i+1,9).setValue(done);s.getRange(i+1,12).setNumberFormat("@").setValue(stamp);return{ok:true}}if(!done)return{ok:false,error:"ابتدا تعداد انجام‌شده را وارد کنید"};if(done===total)return advance(u,q);const m=resolveNext(from,q);s.getRange(i+1,3).setValue(total-done);s.getRange(i+1,9).setValue(0);s.getRange(i+1,12).setNumberFormat("@").setValue(stamp);const id=nextId(v),row=s.getLastRow()+1,created=String(v[i][10]||stamp);s.getRange(row,2).setNumberFormat("@");s.getRange(row,11,1,3).setNumberFormat("@");s.getRange(row,1,1,13).setValues([[id,String(q.code||v[i][1]),done,String(q.customer||""),"",m.route||String(v[i][5]||""),isTailorRole(m.to)?"خیاط":ROLE_FA[m.to],m.to==="completed"?"تکمیل‌شده":"فعال",0,String(v[i][9]||u.username),created,stamp,m.to==="completed"?stamp:""]]);return{ok:true,id,event:history(id,from,m.to,u,"ارسال بخشی از سفارش مادر "+q.id,stamp)}}
function clearArchive(u){if(u.role!=="admin")return{ok:false,error:"فقط مدیر می‌تواند بایگانی را پاک کند"};const s=sh("سفارش‌ها"),v=s.getDataRange().getValues();let n=0;for(let i=v.length-1;i>=1;i--)if(roleKey(v[i][6])==="completed"){s.deleteRow(i+1);n++}return{ok:true,deleted:n}}
