const API=window.NEBRAS_API_URL||"";
let session=localStorage.getItem("nebras_session")||"",me=null,all=[],users=[],tailorUsers=[],orderView="active",busyIds=new Set(),pollTimer=null;
const $=s=>document.querySelector(s);
const fa={admin:"مدیر",plotter:"پلاتر",calendar:"کلندر",cutting:"برش",laser:"لیزر",sewing:"خیاط قدیمی",sewing1:"خیاط ۱",sewing2:"خیاط ۲",sewing3:"خیاط ۳",warehouse:"انبار",completed:"تکمیل‌شده",new:"ثبت سفارش"};
const isTailorRole=x=>x==="sewing"||/^sewing(?:[1-9]|1\d|20)$/.test(String(x||""));
const activeTailors=()=>tailorUsers.filter(x=>x.active);
const roleLabel=x=>{const t=tailorUsers.find(u=>u.role===x);return t?`خیاط ـ ${t.name}`:(fa[x]||x)};
const cleanPassword=x=>String(x||"").trim().replace(/[۰-۹]/g,c=>"۰۱۲۳۴۵۶۷۸۹".indexOf(c)).replace(/[٠-٩]/g,c=>"٠١٢٣٤٥٦٧٨٩".indexOf(c));
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const stageKey=x=>({"تکمیل‌شده":"completed","تکمیل شده":"completed","خیاط ۱":"sewing1","خیاط ۲":"sewing2","خیاط ۳":"sewing3","خیاط":"sewing","ثبت سفارش":"new"}[String(x||"").trim()]||x);
const isKnownStage=x=>["admin","plotter","calendar","cutting","laser","warehouse","completed","new"].includes(String(x||""))||isTailorRole(x);
const normalizeJob=j=>({...j,stage:stageKey(j.stage),events:(j.events||[]).map(e=>({...e,fromStage:stageKey(e.fromStage),toStage:stageKey(e.toStage)})).filter(e=>isKnownStage(e.fromStage)&&isKnownStage(e.toStage)&&!/^XLS[-_]/i.test(String(e.note||"").trim()))});
const when=x=>String(x||"—").replace(",","");

async function call(action,data={}){if(!API)throw Error("نشانی سرویس هنوز تنظیم نشده است");const read=["list","listUsers"].includes(action),retry=read||action==="login",tries=retry?3:1;for(let n=0;n<tries;n++){try{const url=API+(API.includes("?")?"&":"?")+(read?new URLSearchParams({action,session,request:Date.now()+"-"+n}):"request="+Date.now()+"-"+n),options=read?{method:"GET",cache:"no-store"}:{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8","Accept":"application/json"},body:JSON.stringify({action,session,...data})},r=await fetch(url,options),text=await r.text();let d;try{d=JSON.parse(text)}catch(_){throw new TypeError("invalid_response")}if(!d.ok)throw Error(d.error||"خطای ارتباط");return d}catch(e){if(!(e instanceof TypeError)||n===tries-1){const x=Error(e instanceof TypeError?"پاسخ سامانه دریافت نشد؛ وضعیت واقعی بررسی می‌شود.":e.message);if(e instanceof TypeError)x.code="NO_RESPONSE";throw x}await new Promise(ok=>setTimeout(ok,700+n*500))}}}
async function login(e){e.preventDefault();try{const d=await call("login",{username:$("#username").value.trim(),password:cleanPassword($("#password").value)});session=d.session;localStorage.setItem("nebras_session",session);await load()}catch(x){$("#loginError").textContent=x.message}}
function savePageCache(){try{localStorage.setItem("nebras_page_cache",JSON.stringify({me,all,tailorUsers,at:Date.now()}))}catch(_){}}
function showPageCache(){try{const c=JSON.parse(localStorage.getItem("nebras_page_cache")||"null");if(!c||!c.me||!Array.isArray(c.all))return false;me=c.me;all=c.all.map(normalizeJob);tailorUsers=c.tailorUsers||[];showApp();return true}catch(_){return false}}
function showApp(){$("#login").hidden=true;$("#app").hidden=false;$("#newJob").hidden=me.role!=="admin";$("#manageUsers").hidden=me.role!=="admin";$("#orderTabs").hidden=me.role!=="admin";render();if(!pollTimer)pollTimer=setInterval(()=>load(true),10000)}
async function load(silent=false){try{const d=await call("list");me=d.user;all=(d.jobs||[]).map(normalizeJob);tailorUsers=d.tailors||[];savePageCache();showApp()}catch(e){const expired=/نشست|منقضی/.test(String(e.message||""));if(expired){session="";localStorage.removeItem("nebras_session");localStorage.removeItem("nebras_page_cache");$("#login").hidden=false;$("#app").hidden=true;$("#loginError").textContent=e.message}else if(!silent&&!me)$("#loginError").textContent="ارتباط کند است؛ دوباره تلاش کنید."}}
function stageCount(s){return all.filter(j=>j.stage===s||(s==="sewing1"&&j.stage==="sewing")).length}
function tailorSelect(j){const id=esc(j.id),list=activeTailors();return list.length?`<select id="tailor-${id}" class="tailorSelect" aria-label="انتخاب خیاط">${list.map(t=>`<option value="${esc(t.role)}">${esc(t.name)}</option>`).join("")}</select>`:'<span class="noTailor">خیاط فعالی تعریف نشده است</span>'}
function actions(j){if(!j.canAdvance||j.stage==="completed")return "";if(busyIds.has(String(j.id)))return '<div class="actions"><button disabled>در حال انتقال…</button></div>';const id=Number(j.id);let a="";
  if(j.stage==="plotter")a=`<button onclick="advance(${id})">ارسال همه به کلندر</button>`;
  else if(j.stage==="calendar")a=`${tailorSelect(j)}<button onclick="advance(${id},'cutting')">همه به برش</button><button class="ghost" onclick="advance(${id},'laser')">همه به لیزر</button><button class="ghost direct" ${activeTailors().length?'':'disabled'} onclick="advance(${id},'direct',selectedTailor(${id}))">مستقیم به خیاط انتخاب‌شده</button>`;
  else if(j.stage==="cutting"||j.stage==="laser")a=`${tailorSelect(j)}<button ${activeTailors().length?'':'disabled'} onclick="advance(${id},'',selectedTailor(${id}))">ارسال همه به خیاط انتخاب‌شده</button>`;
  else if(isTailorRole(j.stage))a=`<button onclick="advance(${id})">ارسال همه به انبار</button>`;
  else if(j.stage==="warehouse")a=`<button onclick="advance(${id})">تکمیل همه و بایگانی</button>`;
  a+=`<button class="finish" onclick="openEdit(${id})">ویرایش</button>`;return `<div class="actions">${a}</div>`}
function selectedTailor(id){return $("#tailor-"+id)?.value||activeTailors()[0]?.role||""}
function historyHtml(j){if(!j.events?.length)return "";return `<details class="transferHistory"><summary>مشاهده سابقه انتقال‌ها و توضیحات</summary>${j.events.map(e=>`<p><b>${e.fromStage===e.toStage?"یادداشت "+esc(roleLabel(e.fromStage)):"از "+esc(roleLabel(e.fromStage))+" به "+esc(roleLabel(e.toStage))}</b><span>${esc(when(e.createdAt))}</span>${e.note?`<em>${esc(e.note)}</em>`:""}</p>`).join("")}</details>`}
function render(){const q=$("#search").value.trim().toLowerCase(),active=all.filter(j=>j.stage!=="completed"),archive=all.filter(j=>j.stage==="completed"),source=me.role==="admin"?(orderView==="archive"?archive:active):all,jobs=source.filter(j=>(j.code+" "+j.customer+" "+roleLabel(j.stage)+" "+(j.events||[]).map(e=>e.note||"").join(" ")).toLowerCase().includes(q));$("#activeCount").textContent=active.length;$("#archiveCount").textContent=archive.length;$("#clearArchive").hidden=!(me.role==="admin"&&orderView==="archive");$("#clearArchive").disabled=!archive.length;$("#heading").textContent=me.role==="admin"?(orderView==="archive"?"بایگانی سفارش‌های تکمیل‌شده":"سفارش‌های در حال تولید"):"کارهای واحد "+roleLabel(me.role);$("#count").textContent=jobs.length+" مورد";const stages=["plotter","calendar","cutting","laser",...activeTailors().map(t=>t.role),"warehouse"];$("#stats").innerHTML=me.role==="admin"?stages.map(s=>`<div class="stat ${isTailorRole(s)?'s-tailor':''}"><span>${esc(roleLabel(s))}</span><b>${stageCount(s)}</b></div>`).join(""):"";$("#jobs").innerHTML=jobs.length?jobs.map(j=>{const done=Math.min(+j.quantity,+j.progress||0),remaining=Math.max(0,+j.quantity-done),latestTransfer=j.events?.find(e=>e.fromStage!==e.toStage),latestNote=j.events?.find(e=>e.note),progress=done?`<div class="progressLine"><b>انجام‌شده ${done}</b><span>باقی‌مانده ${remaining}</span></div>`:"",note=latestNote?`<div class="unitNote"><b>توضیحات ${esc(roleLabel(latestNote.fromStage))}</b>${esc(latestNote.note)}<small> ـ ${esc(when(latestNote.createdAt))}</small></div>`:"";return `<article class="job ${j.stage==='completed'?'archived':''}"><div class="jobTop"><div><span class="badge">${esc(roleLabel(j.stage))}</span><h3>${esc(j.code)}</h3></div><b>${esc(j.quantity)} عدد</b></div><div class="meta"><span>مشتری<b>${esc(j.customer||"—")}</b></span><span>تاریخ ثبت<b>${esc(when(j.createdAt))}</b></span><span class="wide">آخرین انتقال<b>${latestTransfer?`از ${esc(roleLabel(latestTransfer.fromStage))} به ${esc(roleLabel(latestTransfer.toStage))} | ${esc(when(latestTransfer.createdAt))}`:"—"}</b></span></div>${progress}${note}${historyHtml(j)}${actions(j)}</article>`}).join(""):`<div class="empty"><h3>${orderView==='archive'?'بایگانی هنوز خالی است':'سفارش بازی وجود ندارد'}</h3><p>${orderView==='archive'?'سفارش‌های تکمیل‌شده اینجا نگهداری می‌شوند.':'سفارش‌های جدید یا در حال تولید اینجا نمایش داده می‌شوند.'}</p></div>`}
function localMove(j,to,event){j.stage=to;j.status=to==="completed"?"تکمیل‌شده":"فعال";j.progress=0;j.updatedAt=event?.createdAt||j.updatedAt;if(to==="completed")j.completedAt=j.updatedAt;if(event)j.events=[event,...(j.events||[])];if(me.role!=="admin")all=all.filter(x=>String(x.id)!==String(j.id));savePageCache();render()}
async function advance(id,route="",tailor=""){const key=String(id);if(busyIds.has(key))return;const j=all.find(x=>String(x.id)===key);if(!j)return;const before=j.stage;busyIds.add(key);render();try{const d=await call("advance",{id,route,tailor});localMove(j,stageKey(d.next),d.event)}catch(e){if(e.code==="NO_RESPONSE"){await new Promise(ok=>setTimeout(ok,900));await load(true);const after=all.find(x=>String(x.id)===key);if(!after||after.stage!==before)return;alert("انتقال در سامانه ثبت نشد؛ لطفاً دوباره تلاش کنید.")}else{alert(e.message);await load(true)}}finally{busyIds.delete(key);render()}}
function updateRemaining(){const total=Math.max(0,+$("#editQuantity").value||0),done=Math.max(0,+$("#editProgress").value||0);$("#editProgress").max=total;$("#editRemaining").textContent="باقی‌مانده در این واحد: "+Math.max(0,total-done)+" عدد"}
function updateEditRoute(){const j=all.find(x=>String(x.id)===String($("#editId").value)),route=$("#editRoute").value;$("#editTailorWrap").hidden=!(j&&(j.stage==="cutting"||j.stage==="laser"||(j.stage==="calendar"&&route==="direct")))}
function openEdit(id){const j=all.find(x=>String(x.id)===String(id));if(!j)return;$("#editId").value=j.id;$("#editCode").value=j.code;$("#editQuantity").value=j.quantity;$("#editCustomer").value=j.customer||"";$("#editProgress").value=j.progress||0;$("#editNote").value="";let routes=[];if(j.stage==="calendar")routes=[["cutting","برش"],["laser","لیزر"],["direct","مستقیم به خیاط"]];$("#editRouteWrap").hidden=!routes.length;$("#editRoute").innerHTML=routes.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join("");$("#editTailor").innerHTML=activeTailors().map(t=>`<option value="${esc(t.role)}">${esc(t.name)}</option>`).join("");$("#editTailorWrap").hidden=!(j.stage==="cutting"||j.stage==="laser");updateEditRoute();updateRemaining();$("#editDialog").showModal()}
async function saveJobEdit(e){e.preventDefault();const j=all.find(x=>String(x.id)===String($("#editId").value));if(!j)return;const total=Math.floor(+$("#editQuantity").value||0),done=Math.floor(+$("#editProgress").value||0),send=e.submitter?.value==="send";if(total<1)return alert("تعداد کل باید حداقل یک باشد");if(done<0||done>total)return alert("تعداد انجام‌شده صحیح نیست");if(send&&!done)return alert("ابتدا تعداد انجام‌شده را وارد کنید");const data={id:j.id,code:$("#editCode").value.trim(),quantity:total,customer:$("#editCustomer").value.trim(),progress:done,sendCompleted:send,route:$("#editRoute").value,tailor:$("#editTailor").value,note:$("#editNote").value.trim()};if(!data.code)return alert("کد محصول را وارد کنید");const key=String(j.id);busyIds.add(key);$("#editDialog").close();try{await call("editJob",data);await load(true)}catch(x){alert(x.message);await load(true)}finally{busyIds.delete(key);render()}}
function resetUserForm(){$("#userForm").reset();$("#userOriginal").value="";$("#userActive").checked=true;$("#userPassword").required=true;$("#userPassword").placeholder="رمز عبور";$("#userFormTitle").textContent="کاربر جدید";$("#saveUser").textContent="ساخت حساب"}
function renderUsers(){$("#usersList").innerHTML=users.map((u,i)=>`<button type="button" class="userRow ${u.active?'':'inactive'}" onclick="editUser(${i})"><span><b>${esc(u.name)}</b><small>${esc(u.username)}</small></span><span>${esc(roleLabel(u.role))}<small>${u.active?'فعال':'غیرفعال'}</small></span></button>`).join("")||'<p class="emptyUsers">کاربری ثبت نشده است.</p>'}
async function openUsers(){try{const d=await call("listUsers");users=d.users||[];tailorUsers=users.filter(u=>isTailorRole(u.role));renderUsers();resetUserForm();$("#userDialog").showModal()}catch(e){alert(e.message)}}
function editUser(i){const u=users[i];$("#userOriginal").value=u.username;$("#userName").value=u.name;$("#userUsername").value=u.username;$("#userPassword").value="";$("#userPassword").required=false;$("#userPassword").placeholder="رمز جدید (اگر تغییر نمی‌کند خالی بگذارید)";$("#userRole").value=isTailorRole(u.role)?"sewing_new":u.role;$("#userActive").checked=u.active;$("#userFormTitle").textContent="ویرایش "+u.name;$("#saveUser").textContent="ذخیره تغییرات";$("#userForm").scrollIntoView({behavior:"smooth",block:"start"})}
async function clearArchive(){const n=all.filter(j=>j.stage==="completed").length;if(!n||!confirm("همه "+n+" سفارش بایگانی‌شده برای همیشه حذف شوند؟"))return;const b=$("#clearArchive");b.disabled=true;b.textContent="در حال پاک‌کردن…";try{const d=await call("clearArchive");all=all.filter(j=>j.stage!=="completed");savePageCache();render();alert((d.deleted||n)+" سفارش از بایگانی حذف شد.")}catch(e){alert(e.message)}finally{b.disabled=false;b.textContent="پاک‌کردن بایگانی"}}
$("#cancelEdit").onclick=()=>$("#editDialog").close();$("#editQuantity").oninput=updateRemaining;$("#editProgress").oninput=updateRemaining;$("#editRoute").onchange=updateEditRoute;$("#editForm").addEventListener("submit",saveJobEdit);$("#loginForm").addEventListener("submit",login);$("#search").addEventListener("input",render);$("#refresh").onclick=()=>load();$("#clearArchive").onclick=clearArchive;$("#logout").onclick=()=>{localStorage.removeItem("nebras_session");localStorage.removeItem("nebras_page_cache");location.reload()};$("#newJob").onclick=()=>$("#jobDialog").showModal();$("#cancelJob").onclick=()=>{$("#jobDialog").close();$("#jobForm").reset()};$("#manageUsers").onclick=openUsers;$("#closeUsers").onclick=()=>$("#userDialog").close();$("#cancelUser").onclick=resetUserForm;
$("#userForm").addEventListener("submit",async e=>{e.preventDefault();const original=$("#userOriginal").value,action=original?"updateUser":"addUser",data={originalUsername:original,name:$("#userName").value.trim(),username:$("#userUsername").value.trim(),password:cleanPassword($("#userPassword").value),role:$("#userRole").value,active:$("#userActive").checked};try{await call(action,data);alert(original?"تغییرات کاربر ذخیره شد":"حساب کاربر ساخته شد");const d=await call("listUsers");users=d.users||[];tailorUsers=users.filter(u=>isTailorRole(u.role));renderUsers();resetUserForm();await load(true)}catch(x){alert(x.message||"ذخیره انجام نشد")}});
$("#jobForm").addEventListener("submit",async e=>{e.preventDefault();const b=$("#saveJob");b.disabled=true;try{await call("add",{code:$("#code").value.trim(),quantity:+$("#quantity").value,customer:$("#customer").value.trim()});$("#jobDialog").close();e.target.reset();await load(true)}catch(x){alert(x.message)}finally{b.disabled=false}});
document.querySelectorAll("#orderTabs button").forEach(btn=>btn.onclick=()=>{orderView=btn.dataset.view;document.querySelectorAll("#orderTabs button").forEach(x=>{x.classList.toggle("selected",x===btn);x.classList.toggle("ghost",x!==btn)});render()});
if(session){showPageCache();load()}
