const API=window.NEBRAS_API_URL||"";let session=localStorage.getItem("nebras_session")||"",me=null,all=[],users=[],orderView="active",actionBusy=false,busyIds=new Set();
const $=s=>document.querySelector(s), fa={admin:"مدیر",plotter:"پلاتر",calendar:"کلندر",cutting:"برش",laser:"لیزر",sewing:"خیاط",warehouse:"انبار",completed:"تکمیل‌شده"};
const cleanPassword=x=>String(x||"").trim().replace(/[۰-۹]/g,c=>"۰۱۲۳۴۵۶۷۸۹".indexOf(c)).replace(/[٠-٩]/g,c=>"٠١٢٣٤٥٦٧٨٩".indexOf(c));
const stageKey=x=>({"تکمیل‌شده":"completed","تکمیل شده":"completed"}[String(x||"").trim()]||x);
async function call(action,data={}){if(!API)throw Error("نشانی سرویس هنوز تنظیم نشده است");const safeRetry=["login","list","listUsers"].includes(action),tries=safeRetry?3:1;for(let attempt=0;attempt<tries;attempt++){try{const url=API+(API.includes("?")?"&":"?")+"request="+Date.now()+"-"+attempt,r=await fetch(url,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8","Accept":"application/json"},body:JSON.stringify({action,session,...data})}),text=await r.text();let d;try{d=JSON.parse(text)}catch(_){throw new TypeError("invalid_response")}if(!d.ok)throw Error(d.error||"خطای ارتباط");return d}catch(e){if(!(e instanceof TypeError)||attempt===tries-1)throw Error(e instanceof TypeError?"پاسخ سامانه دریافت نشد؛ دوباره تلاش کنید.":e.message);await new Promise(ok=>setTimeout(ok,1000+attempt*700))}}}
async function updateUserSafe(data){if(users.some(u=>u.username===data.username&&u.username!==data.originalUsername))throw Error("این نام کاربری قبلاً استفاده شده است");await fetch(API+"?save="+Date.now(),{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action:"updateUser",session,...data})});await new Promise(ok=>setTimeout(ok,1400));let d;try{d=await call("listUsers")}catch(_){return null}const saved=(d.users||[]).find(u=>u.username===data.username&&u.name===data.name&&u.role===data.role&&u.active===data.active);if(!saved)throw Error("تغییرات ذخیره نشد؛ اطلاعات واردشده را بررسی کنید.");return d}
async function login(e){e.preventDefault();try{const d=await call("login",{username:$("#username").value.trim(),password:cleanPassword($("#password").value)});session=d.session;localStorage.setItem("nebras_session",session);await load()}catch(e){$("#loginError").textContent=e.message}}
function showApp(){$("#login").hidden=true;$("#app").hidden=false;$("#newJob").hidden=me.role!=="admin";$("#manageUsers").hidden=me.role!=="admin";$("#orderTabs").hidden=me.role!=="admin";render()}
function savePageCache(){try{localStorage.setItem("nebras_page_cache",JSON.stringify({me,all,at:Date.now()}))}catch(_){}}
function showPageCache(){try{const c=JSON.parse(localStorage.getItem("nebras_page_cache")||"null");if(!c||!c.me||!Array.isArray(c.all))return false;me=c.me;all=c.all.map(j=>({...j,stage:stageKey(j.stage)}));showApp();return true}catch(_){return false}}
async function load(){try{const d=await call("list");me=d.user;all=(d.jobs||[]).map(j=>({...j,stage:stageKey(j.stage)}));savePageCache();showApp()}catch(e){const expired=/نشست|منقضی/.test(String(e.message||""));if(expired){session="";localStorage.removeItem("nebras_session");localStorage.removeItem("nebras_page_cache");$("#login").hidden=false;$("#app").hidden=true;$("#loginError").textContent=e.message}else if(!me){$("#loginError").textContent="ارتباط کند است؛ دوباره تلاش کنید."}}}
function jobActions(j){if(busyIds.has(String(j.id)))return '<div class="actions"><button disabled>در حال ثبت…</button></div>';if(!j.canAdvance||j.stage==="completed")return "";let next=j.stage==="plotter"?'<button onclick="advance('+j.id+')">ارسال همه به کلندر</button>':j.stage==="calendar"?'<button onclick="advance('+j.id+',\'cutting\')">همه به برش</button><button class="ghost" onclick="advance('+j.id+',\'laser\')">همه به لیزر</button>':j.stage==="cutting"?'<button onclick="advance('+j.id+')">ارسال همه به خیاطی</button>':j.stage==="laser"?'<button onclick="advance('+j.id+',\'sewing\')">همه به خیاطی</button><button class="ghost" onclick="advance('+j.id+',\'warehouse\')">همه به انبار</button>':j.stage==="sewing"?'<button onclick="advance('+j.id+')">ارسال همه به انبار</button>':j.stage==="warehouse"?'<button onclick="advance('+j.id+')">تکمیل همه و بایگانی</button>':'';next+='<button class="finish" onclick="openEdit('+j.id+')">ویرایش</button>';return '<div class="actions">'+next+'</div>'}
function render(){const q=$("#search").value.trim().toLowerCase(),active=all.filter(j=>j.stage!=="completed"),archive=all.filter(j=>j.stage==="completed"),source=me.role==="admin"?(orderView==="archive"?archive:active):all,jobs=source.filter(j=>(j.code+" "+j.customer+" "+j.occasion).toLowerCase().includes(q));$("#activeCount").textContent=active.length;$("#archiveCount").textContent=archive.length;$("#clearArchive").hidden=!(me.role==="admin"&&orderView==="archive");$("#clearArchive").disabled=!archive.length;$("#heading").textContent=me.role==="admin"?(orderView==="archive"?"بایگانی سفارش‌های تکمیل‌شده":"سفارش‌های در حال تولید"):"کارهای واحد "+(fa[me.role]||me.role);$("#count").textContent=jobs.length+" مورد";const stages=["plotter","calendar","cutting","laser","sewing","warehouse"];$("#stats").innerHTML=me.role==="admin"?stages.map(s=>`<div class="stat"><span>${fa[s]}</span><b>${all.filter(j=>j.stage===s).length}</b></div>`).join(""):"";$("#jobs").innerHTML=jobs.length?jobs.map(j=>{const done=Math.min(+j.quantity,+j.progress||0),remaining=Math.max(0,+j.quantity-done),progress=done?`<div class="progressLine"><b>انجام‌شده ${done}</b><span>باقی‌مانده ${remaining}</span></div>`:"";return `<article class="job ${j.stage==='completed'?'archived':''}"><div class="jobTop"><div><span class="badge">${fa[j.stage]||j.stage}</span><h3>${j.code}</h3></div><b>${j.quantity} عدد</b></div><div class="meta"><span>مشتری<b>${j.customer||"—"}</b></span><span>مناسبت<b>${j.occasion||"—"}</b></span></div>${progress}${jobActions(j)}</article>`}).join(""):`<div class="empty"><h3>${orderView==='archive'?'بایگانی هنوز خالی است':'سفارش بازی وجود ندارد'}</h3><p>${orderView==='archive'?'سفارش‌های تکمیل‌شده اینجا نگهداری می‌شوند.':'سفارش‌های جدید یا در حال تولید اینجا نمایش داده می‌شوند.'}</p></div>`}
function lockActions(on){actionBusy=on;document.querySelectorAll(".actions button").forEach(b=>b.disabled=on)}
function nextStage(stage,route){return stage==="plotter"?"calendar":stage==="calendar"?route:stage==="cutting"?"sewing":stage==="laser"?route:stage==="sewing"?"warehouse":stage==="warehouse"?"completed":""}
async function sendOnce(action,data){await fetch(API+"?change="+Date.now(),{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,session,...data})})}
async function syncAfterAction(){for(let n=0;n<3;n++){if(n)await new Promise(ok=>setTimeout(ok,1400));try{const d=await call("list");me=d.user;all=(d.jobs||[]).map(j=>({...j,stage:stageKey(j.stage)}));render();return}catch(_){}}}
function showStageImmediately(id,target){if(me.role==="admin"){const job=all.find(j=>String(j.id)===String(id));if(job){job.stage=target;job.canAdvance=true}}else all=all.filter(j=>String(j.id)!==String(id));render()}
async function advance(id,route=""){const key=String(id);if(busyIds.has(key))return;const job=all.find(j=>String(j.id)===key),target=job&&nextStage(job.stage,route);if(!target)return alert("مرحله بعد مشخص نیست");const previous=all.map(j=>({...j}));busyIds.add(key);showStageImmediately(id,target);sendOnce("advance",{id,route}).then(()=>syncAfterAction()).catch(async()=>{all=previous;render();await syncAfterAction()}).finally(()=>{busyIds.delete(key);render()})}
async function completeJob(id){if(actionBusy||!confirm("این سفارش مستقیماً تکمیل و به بایگانی منتقل شود؟"))return;const key=String(id),previous=all.map(j=>({...j}));busyIds.add(key);showStageImmediately(id,"completed");sendOnce("complete",{id}).then(()=>syncAfterAction()).catch(async()=>{all=previous;render();await syncAfterAction()}).finally(()=>{busyIds.delete(key);render()})}
function updateRemaining(){const total=Math.max(0,+$("#editQuantity").value||0),done=Math.max(0,+$("#editProgress").value||0);$("#editProgress").max=total;$("#editRemaining").textContent="باقی‌مانده در این واحد: "+Math.max(0,total-done)+" عدد"}
function openEdit(id){const j=all.find(x=>String(x.id)===String(id));if(!j)return;$("#editId").value=j.id;$("#editCode").value=j.code;$("#editQuantity").value=j.quantity;$("#editCustomer").value=j.customer||"";$("#editOccasion").value=j.occasion||"";$("#editProgress").value=j.progress||0;const routes=j.stage==="calendar"?[["cutting","برش"],["laser","لیزر"]]:j.stage==="laser"?[["sewing","خیاطی"],["warehouse","انبار"]]:[];$("#editRouteWrap").hidden=!routes.length;$("#editRoute").innerHTML=routes.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join("");updateRemaining();$("#editDialog").showModal()}
async function saveJobEdit(e){e.preventDefault();const j=all.find(x=>String(x.id)===String($("#editId").value));if(!j)return;const total=Math.floor(+$("#editQuantity").value||0),done=Math.floor(+$("#editProgress").value||0),send=e.submitter&&e.submitter.value==="send";if(total<1)return alert("تعداد کل باید حداقل یک باشد");if(done<0||done>total)return alert("تعداد انجام‌شده صحیح نیست");if(send&&!done)return alert("ابتدا تعداد انجام‌شده را وارد کنید");const data={id:j.id,code:$("#editCode").value.trim(),quantity:total,customer:$("#editCustomer").value.trim(),occasion:$("#editOccasion").value.trim(),progress:done,sendCompleted:send,route:$("#editRoute").value};if(!data.code)return alert("کد محصول را وارد کنید");const key=String(j.id);busyIds.add(key);$("#editDialog").close();if(send){if(done<total){j.quantity=total-done;j.progress=0;j.code=data.code;j.customer=data.customer;j.occasion=data.occasion;render()}else showStageImmediately(j.id,nextStage(j.stage,data.route))}else{Object.assign(j,{code:data.code,quantity:total,customer:data.customer,occasion:data.occasion,progress:done});render()}sendOnce("editJob",data).then(async()=>{await new Promise(ok=>setTimeout(ok,1200));await syncAfterAction()}).catch(()=>{}).finally(()=>{busyIds.delete(key);render()})}
function resetUserForm(){$("#userForm").reset();$("#userOriginal").value="";$("#userActive").checked=true;$("#userPassword").required=true;$("#userPassword").placeholder="رمز عبور";$("#userFormTitle").textContent="کاربر جدید";$("#saveUser").textContent="ساخت حساب"}
function renderUsers(){ $("#usersList").innerHTML=users.map((u,i)=>`<button type="button" class="userRow ${u.active?'':'inactive'}" onclick="editUser(${i})"><span><b>${u.name}</b><small>${u.username}</small></span><span>${fa[u.role]||u.role}<small>${u.active?'فعال':'غیرفعال'}</small></span></button>`).join("")||'<p class="emptyUsers">کاربری ثبت نشده است.</p>' }
async function openUsers(){try{const d=await call("listUsers");users=d.users||[];renderUsers();resetUserForm();$("#userDialog").showModal()}catch(e){alert(e.message)}}
function editUser(i){const u=users[i];$("#userOriginal").value=u.username;$("#userName").value=u.name;$("#userUsername").value=u.username;$("#userPassword").value="";$("#userPassword").required=false;$("#userPassword").placeholder="رمز جدید (اگر تغییر نمی‌کند خالی بگذارید)";$("#userRole").value=u.role;$("#userActive").checked=u.active;$("#userFormTitle").textContent="ویرایش "+u.name;$("#saveUser").textContent="ذخیره تغییرات";$("#userForm").scrollIntoView({behavior:"smooth",block:"start"})}
async function clearArchive(){const count=all.filter(j=>j.stage==="completed").length;if(!count)return;if(!confirm("همه "+count+" سفارش بایگانی‌شده برای همیشه حذف شوند؟"))return;const button=$("#clearArchive");button.disabled=true;button.textContent="در حال پاک‌کردن…";try{const d=await call("clearArchive");all=all.filter(j=>j.stage!=="completed");savePageCache();render();alert((d.deleted||count)+" سفارش از بایگانی حذف شد.")}catch(e){alert(e.message)}finally{button.disabled=false;button.textContent="پاک‌کردن بایگانی"}}
$("#cancelEdit").onclick=()=>$("#editDialog").close();$("#editQuantity").oninput=updateRemaining;$("#editProgress").oninput=updateRemaining;$("#editForm").addEventListener("submit",saveJobEdit);
$("#loginForm").addEventListener("submit",login);$("#search").addEventListener("input",render);$("#refresh").onclick=load;$("#clearArchive").onclick=clearArchive;$("#logout").onclick=()=>{localStorage.removeItem("nebras_session");localStorage.removeItem("nebras_page_cache");location.reload()};$("#newJob").onclick=()=>$("#jobDialog").showModal();$("#cancelJob").onclick=()=>{$("#jobDialog").close();$("#jobForm").reset()};$("#manageUsers").onclick=openUsers;$("#closeUsers").onclick=()=>$("#userDialog").close();$("#cancelUser").onclick=resetUserForm;$("#userForm").addEventListener("submit",async e=>{e.preventDefault();const original=$("#userOriginal").value,action=original?"updateUser":"addUser",data={originalUsername:original,name:$("#userName").value.trim(),username:$("#userUsername").value.trim(),password:cleanPassword($("#userPassword").value),role:$("#userRole").value,active:$("#userActive").checked};try{const d=original?await updateUserSafe(data):await call(action,data);alert(original?"تغییرات کاربر ذخیره شد":"حساب کاربر ساخته شد");resetUserForm();if(d&&d.users){users=d.users;renderUsers()}else try{const fresh=await call("listUsers");users=fresh.users||[];renderUsers()}catch(_){$("#userDialog").close()}}catch(x){alert(x.message||"ذخیره انجام نشد")}});$("#jobForm").addEventListener("submit",async e=>{e.preventDefault();try{await call("add",{code:$("#code").value.trim(),quantity:+$("#quantity").value,customer:$("#customer").value.trim(),occasion:$("#occasion").value.trim()});$("#jobDialog").close();e.target.reset();await load()}catch(x){alert(x.message)}});document.querySelectorAll("#orderTabs button").forEach(btn=>btn.onclick=()=>{orderView=btn.dataset.view;document.querySelectorAll("#orderTabs button").forEach(x=>{x.classList.toggle("selected",x===btn);x.classList.toggle("ghost",x!==btn)});render()});if(session){showPageCache();load()}
