const API=window.NEBRAS_API_URL||"";let session=localStorage.getItem("nebras_session")||"",me=null,all=[],users=[],orderView="active",actionBusy=false,busyIds=new Set();
const $=s=>document.querySelector(s), fa={admin:"مدیر",plotter:"پلاتر",calendar:"کلندر",cutting:"برش",laser:"لیزر",sewing:"خیاط",warehouse:"انبار",completed:"تکمیل‌شده"};
const cleanPassword=x=>String(x||"").trim().replace(/[۰-۹]/g,c=>"۰۱۲۳۴۵۶۷۸۹".indexOf(c)).replace(/[٠-٩]/g,c=>"٠١٢٣٤٥٦٧٨٩".indexOf(c));
const stageKey=x=>({"تکمیل‌شده":"completed","تکمیل شده":"completed"}[String(x||"").trim()]||x);
async function call(action,data={}){if(!API)throw Error("نشانی سرویس هنوز تنظیم نشده است");let last;for(let attempt=0;attempt<2;attempt++){try{const r=await fetch(API,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,session,...data})});const d=await r.json();if(!d.ok)throw Error(d.error||"خطای ارتباط");return d}catch(e){last=e;if(!(e instanceof TypeError)||attempt)return Promise.reject(e);await new Promise(ok=>setTimeout(ok,900))}}throw last}
async function updateUserSafe(data){if(users.some(u=>u.username===data.username&&u.username!==data.originalUsername))throw Error("این نام کاربری قبلاً استفاده شده است");await fetch(API+"?save="+Date.now(),{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action:"updateUser",session,...data})});await new Promise(ok=>setTimeout(ok,1400));let d;try{d=await call("listUsers")}catch(_){return null}const saved=(d.users||[]).find(u=>u.username===data.username&&u.name===data.name&&u.role===data.role&&u.active===data.active);if(!saved)throw Error("تغییرات ذخیره نشد؛ اطلاعات واردشده را بررسی کنید.");return d}
async function login(e){e.preventDefault();try{const d=await call("login",{username:$("#username").value.trim(),password:cleanPassword($("#password").value)});session=d.session;localStorage.setItem("nebras_session",session);await load()}catch(e){$("#loginError").textContent=e.message}}
async function load(){try{const d=await call("list");me=d.user;all=(d.jobs||[]).map(j=>({...j,stage:stageKey(j.stage)}));$("#login").hidden=true;$("#app").hidden=false;$("#newJob").hidden=me.role!=="admin";$("#manageUsers").hidden=me.role!=="admin";$("#orderTabs").hidden=me.role!=="admin";render()}catch(e){session="";localStorage.removeItem("nebras_session");$("#login").hidden=false;$("#app").hidden=true;$("#loginError").textContent=e.message}}
function jobActions(j){if(busyIds.has(String(j.id)))return '<div class="actions"><button disabled>در حال ثبت…</button></div>';if(!j.canAdvance||j.stage==="completed")return "";let next=j.stage==="plotter"?'<button onclick="advance('+j.id+')">ارسال به کلندر</button>':j.stage==="calendar"?'<button onclick="advance('+j.id+',\'cutting\')">ارسال به برش</button><button class="ghost" onclick="advance('+j.id+',\'laser\')">ارسال به لیزر</button>':j.stage==="cutting"?'<button onclick="advance('+j.id+')">ارسال به خیاطی</button>':j.stage==="laser"?'<button onclick="advance('+j.id+',\'sewing\')">ارسال به خیاطی</button><button class="ghost" onclick="advance('+j.id+',\'warehouse\')">ارسال مستقیم به انبار</button>':j.stage==="sewing"?'<button onclick="advance('+j.id+')">ارسال به انبار</button>':j.stage==="warehouse"?'<button onclick="advance('+j.id+')">تکمیل و بایگانی</button>':'';if(me.role==="admin"&&j.stage!=="warehouse")next+='<button class="finish" onclick="completeJob('+j.id+')">تکمیل مستقیم و بایگانی</button>';return '<div class="actions">'+next+'</div>'}
function render(){const q=$("#search").value.trim().toLowerCase(),active=all.filter(j=>j.stage!=="completed"),archive=all.filter(j=>j.stage==="completed"),source=me.role==="admin"?(orderView==="archive"?archive:active):all,jobs=source.filter(j=>(j.code+" "+j.customer+" "+j.occasion).toLowerCase().includes(q));$("#activeCount").textContent=active.length;$("#archiveCount").textContent=archive.length;$("#heading").textContent=me.role==="admin"?(orderView==="archive"?"بایگانی سفارش‌های تکمیل‌شده":"سفارش‌های در حال تولید"):"کارهای واحد "+(fa[me.role]||me.role);$("#count").textContent=jobs.length+" مورد";const stages=["plotter","calendar","cutting","laser","sewing","warehouse"];$("#stats").innerHTML=me.role==="admin"?stages.map(s=>`<div class="stat"><span>${fa[s]}</span><b>${all.filter(j=>j.stage===s).length}</b></div>`).join(""):"";$("#jobs").innerHTML=jobs.length?jobs.map(j=>`<article class="job ${j.stage==='completed'?'archived':''}"><div class="jobTop"><div><span class="badge">${fa[j.stage]||j.stage}</span><h3>${j.code}</h3></div><b>${j.quantity} عدد</b></div><div class="meta"><span>مشتری<b>${j.customer||"—"}</b></span><span>مناسبت<b>${j.occasion||"—"}</b></span></div>${jobActions(j)}</article>`).join(""):`<div class="empty"><h3>${orderView==='archive'?'بایگانی هنوز خالی است':'سفارش بازی وجود ندارد'}</h3><p>${orderView==='archive'?'سفارش‌های تکمیل‌شده اینجا نگهداری می‌شوند.':'سفارش‌های جدید یا در حال تولید اینجا نمایش داده می‌شوند.'}</p></div>`}
function lockActions(on){actionBusy=on;document.querySelectorAll(".actions button").forEach(b=>b.disabled=on)}
function nextStage(stage,route){return stage==="plotter"?"calendar":stage==="calendar"?route:stage==="cutting"?"sewing":stage==="laser"?route:stage==="sewing"?"warehouse":stage==="warehouse"?"completed":""}
async function sendOnce(action,data){await fetch(API+"?change="+Date.now(),{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,session,...data})})}
async function syncAfterAction(){for(let n=0;n<3;n++){if(n)await new Promise(ok=>setTimeout(ok,1400));try{const d=await call("list");me=d.user;all=(d.jobs||[]).map(j=>({...j,stage:stageKey(j.stage)}));render();return}catch(_){}}}
function showStageImmediately(id,target){if(me.role==="admin"){const job=all.find(j=>String(j.id)===String(id));if(job){job.stage=target;job.canAdvance=true}}else all=all.filter(j=>String(j.id)!==String(id));render()}
async function advance(id,route=""){const key=String(id);if(busyIds.has(key))return;const job=all.find(j=>String(j.id)===key),target=job&&nextStage(job.stage,route);if(!target)return alert("مرحله بعد مشخص نیست");const previous=all.map(j=>({...j}));busyIds.add(key);showStageImmediately(id,target);sendOnce("advance",{id,route}).then(()=>syncAfterAction()).catch(async()=>{all=previous;render();await syncAfterAction()}).finally(()=>{busyIds.delete(key);render()})}
async function completeJob(id){if(actionBusy||!confirm("این سفارش مستقیماً تکمیل و به بایگانی منتقل شود؟"))return;lockActions(true);try{await call("complete",{id});await load()}catch(e){alert(e.message)}finally{lockActions(false)}}
function resetUserForm(){$("#userForm").reset();$("#userOriginal").value="";$("#userActive").checked=true;$("#userPassword").required=true;$("#userPassword").placeholder="رمز عبور";$("#userFormTitle").textContent="کاربر جدید";$("#saveUser").textContent="ساخت حساب"}
function renderUsers(){ $("#usersList").innerHTML=users.map((u,i)=>`<button type="button" class="userRow ${u.active?'':'inactive'}" onclick="editUser(${i})"><span><b>${u.name}</b><small>${u.username}</small></span><span>${fa[u.role]||u.role}<small>${u.active?'فعال':'غیرفعال'}</small></span></button>`).join("")||'<p class="emptyUsers">کاربری ثبت نشده است.</p>' }
async function openUsers(){try{const d=await call("listUsers");users=d.users||[];renderUsers();resetUserForm();$("#userDialog").showModal()}catch(e){alert(e.message)}}
function editUser(i){const u=users[i];$("#userOriginal").value=u.username;$("#userName").value=u.name;$("#userUsername").value=u.username;$("#userPassword").value="";$("#userPassword").required=false;$("#userPassword").placeholder="رمز جدید (اگر تغییر نمی‌کند خالی بگذارید)";$("#userRole").value=u.role;$("#userActive").checked=u.active;$("#userFormTitle").textContent="ویرایش "+u.name;$("#saveUser").textContent="ذخیره تغییرات";$("#userForm").scrollIntoView({behavior:"smooth",block:"start"})}
$("#loginForm").addEventListener("submit",login);$("#search").addEventListener("input",render);$("#refresh").onclick=load;$("#logout").onclick=()=>{localStorage.removeItem("nebras_session");location.reload()};$("#newJob").onclick=()=>$("#jobDialog").showModal();$("#cancelJob").onclick=()=>{$("#jobDialog").close();$("#jobForm").reset()};$("#manageUsers").onclick=openUsers;$("#closeUsers").onclick=()=>$("#userDialog").close();$("#cancelUser").onclick=resetUserForm;$("#userForm").addEventListener("submit",async e=>{e.preventDefault();const original=$("#userOriginal").value,action=original?"updateUser":"addUser",data={originalUsername:original,name:$("#userName").value.trim(),username:$("#userUsername").value.trim(),password:cleanPassword($("#userPassword").value),role:$("#userRole").value,active:$("#userActive").checked};try{const d=original?await updateUserSafe(data):await call(action,data);alert(original?"تغییرات کاربر ذخیره شد":"حساب کاربر ساخته شد");resetUserForm();if(d&&d.users){users=d.users;renderUsers()}else try{const fresh=await call("listUsers");users=fresh.users||[];renderUsers()}catch(_){$("#userDialog").close()}}catch(x){alert(x.message||"ذخیره انجام نشد")}});$("#jobForm").addEventListener("submit",async e=>{e.preventDefault();try{await call("add",{code:$("#code").value.trim(),quantity:+$("#quantity").value,customer:$("#customer").value.trim(),occasion:$("#occasion").value.trim()});$("#jobDialog").close();e.target.reset();await load()}catch(x){alert(x.message)}});document.querySelectorAll("#orderTabs button").forEach(btn=>btn.onclick=()=>{orderView=btn.dataset.view;document.querySelectorAll("#orderTabs button").forEach(x=>{x.classList.toggle("selected",x===btn);x.classList.toggle("ghost",x!==btn)});render()});if(session)load();
